import Header from "@/components/Header"
import "modern-css-reset"
import type { Metadata } from "next"
import { Nunito_Sans } from "next/font/google"
import Providers from "./libs/providers"
import "./styles/globals.scss"

const nunito = Nunito_Sans({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={nunito.className}>
        <Providers>
          <Header />
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  )
}
