import Header from "@/components/Header"
import type { Metadata } from "next"
import { Nunito_Sans } from "next/font/google"
import Providers from "./libs/providers"

import MainLayout from "@/components/MainLayout"
import "modern-css-reset"
import "./styles/globals.scss"

const nunito = Nunito_Sans({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: {
    default: "Webcomponent Asset",
    template: "%s - Webcomponent Asset",
  },
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={nunito.className}>
        <Providers>
          <Header />
          <MainLayout>{children}</MainLayout>
        </Providers>
      </body>
    </html>
  )
}
